name: iOS Build & Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install Flutter dependencies
        run: flutter pub get
        
      - name: Install CocoaPods
        run: |
          cd ios
          pod install
          
      - name: Build iOS
        run: flutter build ios --release --no-codesign
        
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.FIREBASE_SERVICE_ACCOUNT}}
          groups: testers
          file: build/ios/iphoneos/Runner.app
