name: iOS Build & Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install Flutter dependencies
        run: flutter pub get
        
      - name: Install CocoaPods
        run: |
          cd ios
          pod install
          
      - name: Build iOS IPA
        run: |
          flutter build ipa --release --no-codesign
          echo "Checking build directory contents:"
          ls -R build/ios/
          
      - name: Show IPA Location
        run: |
          find build -name "*.ipa" -type f
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-ipa
          path: |
            build/**/*.ipa
            
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      - name: Deploy to Firebase App Distribution
        run: |
          IPA_PATH=$(find build -name "*.ipa" -type f)
          if [ -n "$IPA_PATH" ]; then
            echo "Found IPA at: $IPA_PATH"
            firebase appdistribution:distribute "$IPA_PATH" \
              --app ${{ secrets.FIREBASE_APP_ID }} \
              --token ${{ secrets.FIREBASE_TOKEN }} \
              --groups testers
          else
            echo "No IPA file found"
            exit 1
          fi
